version: '3.7'

services:

  potter:
    build: ./potter
    container_name: potter
    restart: always
    command: bash -c "/potter/wait_for_mysql.sh && gunicorn -w 5 --timeout 300 -b :8000 run:app"
    expose:
      - 8000
    depends_on:
      - db
    environment:
      POTTER_MYSQL_HOST: "192.168.20.150"
      POTTER_MYSQL_PASSWORD: "${DB_PASSWORD}"
      POTTER_SECRET_KEY: "${POTTER_SECRET_KEY}"
      POTTER_VT_MASTER_KEY: "${VT_MASTER_KEY}"
    networks:
      potternet:
        ipv4_address: 192.168.30.99

  db:
    build: ./docker/mariadb
    container_name: potter_db
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: potter
      MYSQL_USER: potter
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    networks:
      potternet:
        ipv4_address: 192.168.30.98

  nginx:
    build: ./docker/nginx
    container_name: potter_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/certs:/etc/nginx/certs
    depends_on:
      - potter
    networks:
      potternet:
        ipv4_address: 192.168.30.100

networks:
  potternet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.30.100/28